version: '3'

services:
  mms:
    ports:
      - 8088
    image: mmsserver:0.1
    environment:
        - ENV_MNS_HOST=mcm
        - ENV_MNS_PORT=8588
        - ENV_RABBIT_MQ_HOST=rabbitmq-db
        - ENV_RABBIT_MQ_PORT=5672
        - ENV_RABBIT_MQ_MANAGING_HOST=rabbitmq-db
        - ENV_RABBIT_MQ_MANAGING_PORT=15672
        - ENV_RABBIT_MQ_USER=rabbitmq
        - ENV_RABBIT_MQ_PASSWD=rabbitmq
        - ENV_REDIS_HOST=redis
        - ENV_REDIS_PORT=6379
    stdin_open: true
    tty: true
    depends_on:
      - mcm
      - rabbitmq-db
      - redis
#    networks:
#      - mcp-network
  mcm:
    image: mnsdummy:0.1
    ports:
      - 8588
    environment:
      - serverNo=1
    stdin_open: true
    tty: true

  redis:
    image: redis:5.0.3
    ports:
      - 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    command: redis-server /data/redis.conf
    stdin_open: true
    tty: true
    restart: unless-stopped

  rabbitmq-db:
    image: rabbitmq:3-management
    ports:
      - 15672
      - 5672
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    stdin_open: true
    tty: true
    restart: unless-stopped

#networks:
#  mcp-network:
#    external: true

networks:
  default:
    external:
      name: mcp-network
